version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  node:
    restart: on-failure
    build: ./node
    ports:
      - '81:5000'
  nginx:
    image: nginx:1.0.5
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:rw
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    depends_on:
      - node
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
